spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blog_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      stat-view-servlet:
        login-username: admin
        login-password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
